### ISSUE TITLE
smart TOC don't work

### ISSUE THREAD

**Issue by zonetw** [carsonip/hugo-theme-minos#11]
under HUGO version 0.25
I build a whole new site
setup config.toml as below
```
baseURL = "http://example.org/"
languageCode = "en-us"
title = "My New Hugo Site"
theme = "hugo-theme-minos"

[params]
    smartToc = true
```

add one post with command
```
hugo new posts/1.md
```

1.md look like this
```
---
title: "1"
date: 2017-08-05T15:42:46+08:00
draft: false
---

[TOC]

# H1
2222

## H2
444
```

and the result look like this
<img width="281" alt="2017-08-05 15 52 33" src="https://user-images.githubusercontent.com/1495482/28994026-b95da9b8-79f6-11e7-9aaf-2d3d520d792a.png">

can you help me figure it out ? or tell me where the document I can see ?
thanks very much

**Comment by carsonip** [comment]
Hi @zonetw, there is no TOC when window width is smaller than a certain threshold. Try to zoom out and you'll see the TOC on the right. When the page content is too little (i.e. height not enough), smart TOC does not work very well too. This also applies to the last few headings (if their content under the heading are too short) since you cannot scroll past the n-1th heading.

I'm using the exact same version of hugo, same post content and config, and things are working fine.
