### ISSUE TITLE
Changing default font sizes

### ISSUE THREAD

**Issue by kleinbottle** [carsonip/hugo-theme-minos#12]
I am new to Hugo themes and really like Minos for KaTeX support.

Can MathJax support be specified in the source .md file?

I also really like your choice of font but would like it to be larger.

Is there a way to specify a larger font size?

**Comment by carsonip** [comment]
Thanks! The current version of this theme doesn't have MathJax support. Also It shouldn't be hard to implement MathJax by yourself. (and I chose KaTeX because it is much faster)
To specify a larger font size, you can simply change the font size inside the theme css or add a css block to override theme css in some html. The way of changing font size should apply to all hugo themes.
